### PR TITLE
robot init commit

### PR DESCRIPTION
**Pull request by andrey-berdnik**
Created base robot tests. 

Firstly need to install robot framework.
`pip3 install robotframework`

than check installation 
`robot --version`

To run tests:

`cd tests/integration/`
`robot test.robot`

You will receive in console 
image

And in report.html
image

### CODE REVIEW

**Comment by Storegist** [comment]
I guess everything is fine. Just, maybe, First app and Second app instead of "One app" and "Two app" may look better from the English language point of view

**Comment by andrey-berdnik** [comment]
> I guess everything is fine. Just, maybe, First app and Second app instead of "One app" and "Two app" may look better from the English language point of view

The point is that these are script names that describe the launch of only one application or two at the same time. Not  first and second app

**Comment by Storegist** [comment]
Understood

**Review by Storegist — APPROVED** [review]
Approved

**Review by zonmen — APPROVED** [review]
Cool

**Pull request merged**
