### PR TITLE
Cleaning up the project structure 

### PR DESCRIPTION
**Pull request by andrey-berdnik**
- add .gitignore
- update cmake file (add project name, add gmock_main lib)
- Add how-to to readme file
- Add "Course assignment" to doc directory 
- fix typo parce->parse
- fix typo test->tests
- Remove test-code from main function 
- update unit-testing structure for get possibility run all tests by one command

### CODE REVIEW

**Comment by ValentinSidorov** [comment]
Good

**Comment by zonmen** [comment]
Good. Small addition, we need to update Cmake requirements into 3.11 version(because of  using "FetchContent").

**Comment by andrey-berdnik** [comment]
> Good. Small addition, we need to update Cmake requirements into 3.11 version(because of using "FetchContent").

Thanks, updated

**Comment by zonmen** [comment]
One more thing, when I parse test file, int structure stdout_mode always equal false, so something wrong with yaml_parce.cpp
screen

**Comment by andrey-berdnik** [comment]
> * update unit-testing structure for get possibility run all tests by one command

Will be changed in another issue, thanks

**Pull request merged**
